INSERT INTO prison_detail (prison_id, prison_name) VALUES ('AKI', 'Acklington (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('ALI', 'Albany (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('ANI', 'Aldington (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('ACI', 'Altcourse (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('ASI', 'Ashfield (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('AWI', 'Ashwell (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('AGI', 'Askham Grange (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('AYI', 'Aylesbury (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('BFI', 'Bedford (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('BAI', 'Belmarsh (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('BWI', 'Berwyn (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('BMI', 'Birmingham (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('BTI', 'Blakenhurst (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('BHI', 'Blantyre House (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('BDI', 'Blundeston (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('BSI', 'Brinsford (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('BLI', 'Bristol (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('BXI', 'Brixton (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('BKI', 'Brockhill (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('BZI', 'Bronzefield (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('BCI', 'Buckley Hall (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('BNI', 'Bullingdon (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('BUI', 'Bullwood Hall (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('BRI', 'Bure (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('CHI', 'Camp Hill (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('CPI', 'Campsfield House (hmYOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('CYI', 'Canterbury (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('CFI', 'Cardiff (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('CSI', 'Castington (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('CWI', 'Channings Wood (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('CDI', 'Chelmsford (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('CEI', 'Cleland (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('CRI', 'Colchester (hmYOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('CLI', 'Coldingley (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('CKI', 'Cookham Wood (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('DAI', 'Dartmoor (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('DTI', 'Deerbolt (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('DNI', 'Doncaster (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('DRI', 'Dorchester (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('DGI', 'Dovegate (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('DVI', 'Dover Immigration Removal Centre');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('DWI', 'Downview (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('DHI', 'Drake Hall (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('DMI', 'Durham (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('ESI', 'East Sutton Park (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('EWI', 'Eastwood Park (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('NEI', 'Edmunds Hill (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('EYI', 'Elmley (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('EEI', 'Erlestoke (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('EVI', 'Everthorpe (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('EXI', 'Exeter (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('FSI', 'Featherstone (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('FYI', 'Feltham A (HMYOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('FMI', 'Feltham B (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('FII', 'Finnamore (hmYOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('FWI', 'Five Wells (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('FDI', 'Ford (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('FOI', 'Foreign Prison');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('FBI', 'Forest Bank (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('FEI', 'Fosse Way (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('FHI', 'Foston Hall (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('FKI', 'Frankland (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('FNI', 'Full Sutton (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('GHI', 'Garth (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('GTI', 'Gartree (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('ZZGHI', 'Ghost Holding Establishment');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('GPI', 'Glen Parva (HMPYOI & Rc)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('GLI', 'Gloucester (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('GNI', 'Grendon (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('GMI', 'Guys Marsh (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('HRI', 'Haslar Immigration Removal Centre');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('HDI', 'Hatfield (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('HVI', 'Haverigg (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('HGI', 'Hewell Grange (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('HEI', 'Hewell (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('HOI', 'High Down (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('HPI', 'Highpoint (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('HII', 'Hindley (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('HBI', 'Hollesley Bay (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('HYI', 'Holloway (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('HHI', 'Holme House (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('HLI', 'Hull (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('HMI', 'Humber (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('HCI', 'Huntercombe (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('ISI', 'Isis (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('IWI', 'Isle Of Wight (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('KTI', 'Kennet (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('PTI', 'Kingston (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('KMI', 'Kirkham (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('KVI', 'Kirklevington Grange (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('LAI', 'Lancaster Castle (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('LFI', 'Lancaster Farms (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('LMI', 'Latchmere House (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('LEI', 'Leeds (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('LCI', 'Leicester (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('LWI', 'Lewes (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('LYI', 'Leyhill (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('LII', 'Lincoln (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('LHI', 'Lindholme (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('LTI', 'Littlehey (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('LPI', 'Liverpool (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('LLI', 'Long Lartin (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('LGI', 'Lowdham Grange (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('LNI', 'Low Newton (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('MSI', 'Maidstone (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('MRI', 'Manchester (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('MWI', 'Medway (STC)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('MDI', 'Moorland (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('MHI', 'Morton Hall (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('NHI', 'New Hall (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('NNI', 'Northallerton (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('NOI', 'Northeye (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('NSI', 'North Sea Camp (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('NLI', 'Northumberland (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('NWI', 'Norwich (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('NMI', 'Nottingham (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('STC3', 'Oakhill (STC)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('OWI', 'Oakwood (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('ONI', 'Onley (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('OXI', 'Oxford (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('PRI', 'Parc (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('PYI', 'Parc (HMYOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('PKI', 'Parkhurst (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('PVI', 'Pentonville (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('PFI', 'Peterborough Female (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('PBI', 'Peterborough (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('PDI', 'Portland (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('UPI', 'Prescoed (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('PNI', 'Preston (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('PCI', 'Pucklechurch (hmrc)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('STC2', 'Rainsbrook (STC)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('RNI', 'Ranby (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('RDI', 'Reading (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('RSI', 'Risley (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('RCI', 'Rochester (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('RLI', 'Rollestone (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('RUI', 'Rudgate (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('RHI', 'Rye Hill (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('SDI', 'Send (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('SMI', 'Shepton Mallet (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('SYI', 'Shrewsbury (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('SPI', 'Spring Hill (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('SFI', 'Stafford (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('EHI', 'Standford Hill (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('SKI', 'Stocken (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('SHI', 'Stoke Heath (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('STI', 'Styal (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('SUI', 'Sudbury (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('SLI', 'Swaleside (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('SWI', 'Swansea (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('SNI', 'Swinfen Hall (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('TSI', 'Thameside (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('MTI', 'The Mount (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('VEI', 'The Verne (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('WAI', 'The Weare (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('TCI', 'Thorn Cross (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('TAI', 'Thorp Arch (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('UKI', 'Usk (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('WDI', 'Wakefield (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('WWI', 'Wandsworth (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('WII', 'Warren Hill (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('WLI', 'Wayland (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('WEI', 'Wealstun (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('WBI', 'Wellingborough (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('WNI', 'Werrington (HMYOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('WYI', 'Wetherby (HMYOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('WTI', 'Whatton (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('WRI', 'Whitemoor (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('WCI', 'Winchester (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('WOI', 'Wolds (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('WHI', 'Woodhill (HMP & YOI)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('WSI', 'Wormwood Scrubs (HMP)');
INSERT INTO prison_detail (prison_id, prison_name) VALUES ('WMI', 'Wymott (HMP)');
