version: '3.1'
services:

  sar-worker-db:
    image: postgres:17
    networks:
      - hmpps
    container_name: sar-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_USER=admin
      - POSTGRES_DB=sar-db

  sar-renderer-db:
    image: postgres:17
    networks:
      - hmpps
    container_name: sar-db-renderer
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=admin_password
      - POSTGRES_USER=admin
      - POSTGRES_DB=sar-db-renderer

  localstack:
    image: localstack/localstack:3
    networks:
      - hmpps
    container_name: localstack-pl
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"

networks:
  hmpps:
