services:
  hmpps-auth:
    base-url: https://sign-in-dev.hmpps.service.justice.gov.uk
    username: clientid # until we get a client seeded
    password: clientsecret

  sar-api:
    base-url: http://localhost:8080

  document-storage:
    base-url: https://document-api-dev.hmpps.service.justice.gov.uk

