services:
  hmpps-auth:
    base-url: https://sign-in.hmpps.service.justice.gov.uk
    username: ${SYSTEM_CLIENT_ID}
    password: ${SYSTEM_CLIENT_SECRET}

  prison-api:
    base-url: https://prison-api.prison.service.justice.gov.uk

  probation-api:
    base-url: https://subject-access-requests-and-delius.hmpps.service.justice.gov.uk

  sar-api:
    base-url: https://subject-access-request-api.hmpps.service.justice.gov.uk

  document-storage:
    base-url: https://document-api.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENV: prod