services:
  hmpps-auth:
    base-url: https://sign-in-preprod.hmpps.service.justice.gov.uk
    username: ${SYSTEM_CLIENT_ID}
    password: ${SYSTEM_CLIENT_SECRET}

  sar-api:
    base-url: https://subject-access-request-api-preprod.hmpps.service.justice.gov.uk

  document-storage:
    base-url: https://document-api-preprod.hmpps.service.justice.gov.uk

  env:
    SENTRY_ENV: pre-prod