dpsServices:
  - name: keyworker-api
    orderPosition: 1
    businessName: Keyworker
  - name: offender-case-notes
    orderPosition: 2
    businessName: Offender Case Notes
  - name: court-case-service
    orderPosition: 3
    businessName: Prepare a Case for Sentence
  - name: hmpps-restricted-patients-api
    orderPosition: 4
    businessName: Restricted Patients
  - name: hmpps-accredited-programmes-api
    orderPosition: 5
    businessName: Accredited Programmes
  - name: hmpps-complexity-of-need
    orderPosition: 6
    businessName: Complexity of Need
  - name: offender-management-allocation-manager
    orderPosition: 7
    businessName: Manage Prison Offender Manager Cases
  - name: hmpps-book-secure-move-api
    orderPosition: 8
    businessName: Book a Secure Move
  - name: hmpps-education-and-work-plan-api
    orderPosition: 9
    businessName: Personal Learning Plan
  - name: hmpps-non-associations-api
    orderPosition: 10
    businessName: Non-associations
  - name: hmpps-incentives-api
    orderPosition: 11
    businessName: Incentives
  - name: hmpps-manage-adjudications-api
    orderPosition: 12
    businessName: Manage Adjudications
  - name: hmpps-offender-categorisation-api
    orderPosition: 13
    businessName: Categorisation Tool
  - name: make-recall-decision-api
    orderPosition: 14
    businessName: Consider a Recall
  - name: hmpps-hdc-api
    orderPosition: 15
    businessName: Home Detention Curfew
  - name: create-and-vary-a-licence-api
    orderPosition: 16
    businessName: Create and Vary a Licence
  - name: hmpps-uof-data-api
    orderPosition: 17
    businessName: Use of Force
  - name: hmpps-activities-management-api
    orderPosition: 18
    businessName: Manage Activities and Appointments
  - name: hmpps-interventions-service
    orderPosition: 19
    businessName: Refer and Monitor an Intervention
  - name: hmpps-resettlement-passport-api
    orderPosition: 20
    businessName: Prepare Someone for Release
  - name: launchpad-auth
    orderPosition: 21
    businessName: Launchpad