package uk.gov.justice.digital.hmpps.subjectaccessrequestworker.services

import com.google.gson.Gson
import com.itextpdf.kernel.pdf.PdfDocument
import com.itextpdf.kernel.pdf.PdfReader
import com.itextpdf.kernel.pdf.canvas.parser.PdfTextExtractor
import com.itextpdf.layout.Document
import org.apache.commons.lang3.StringUtils
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import uk.gov.justice.digital.hmpps.subjectaccessrequestworker.models.DpsService
import uk.gov.justice.digital.hmpps.subjectaccessrequestworker.models.ReportParameters
import uk.gov.justice.digital.hmpps.subjectaccessrequestworker.models.SubjectAccessRequest
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.InputStreamReader
import java.nio.file.Files
import java.nio.file.Path
import java.time.LocalDate
import java.util.UUID

class PdfServiceTest {

  private lateinit var legacyPdfService: GeneratePdfService
  private lateinit var newPdfService: PdfService

  @TempDir
  private lateinit var tempDir: Path

  companion object {
    const val TEST_DATA_PATH = "service-data-stubs/book-secure-move-test-data.json"
  }

  @BeforeEach
  fun setup() {
    this.legacyPdfService = GeneratePdfService()
    this.newPdfService = PdfService()
  }

  @Test
  fun `PDFs generated by new service matches those generated by legacy service`() {
    val testServiceData = getTestData()
    assertThat(testServiceData).isNotNull

    val params = ReportParameters(
      services = listOf(DpsService(name = "hmpps-book-secure-move-api", orderPosition = 1, content = testServiceData)),
      nomisId = "1234",
      ndeliusCaseReferenceId = "nDeliusRef123",
      sarCaseReferenceNumber = "sarCaseRef",
      subjectName = "Lord Voldemort",
      dateFrom = LocalDate.now().minusYears(1),
      dateTo = LocalDate.now(),
      subjectAccessRequest = SubjectAccessRequest(id = UUID.randomUUID()),
    )

    val legacySarPdf = generateLegacyReport(params).toFile()
    val newSarPdf = generateNewReport(params).toFile()

    assertThat(legacySarPdf.isFile).isTrue()
    assertThat(newSarPdf.isFile).isTrue()
    assertThat(Files.size(legacySarPdf.toPath())).isEqualTo(Files.size(newSarPdf.toPath()))
    assertReportContentsEquals(getDocument(legacySarPdf), getDocument(legacySarPdf))
  }

  @Test
  fun `PDFs generated by new service matches those generated by legacy service when no template is used`() {
    val testServiceData = getTestData()
    assertThat(testServiceData).isNotNull

    val params = ReportParameters(
      services = listOf(DpsService(name = "unknown-template-here", orderPosition = 1, content = testServiceData)),
      nomisId = "1234",
      ndeliusCaseReferenceId = "nDeliusRef123",
      sarCaseReferenceNumber = "sarCaseRef",
      subjectName = "Lord Voldemort",
      dateFrom = LocalDate.now().minusYears(1),
      dateTo = LocalDate.now(),
      subjectAccessRequest = SubjectAccessRequest(id = UUID.randomUUID()),
    )

    val legacySarPdf = generateLegacyReport(params).toFile()
    val newSarPdf = generateNewReport(params).toFile()

    assertThat(legacySarPdf.isFile).isTrue()
    assertThat(newSarPdf.isFile).isTrue()
    assertThat(Files.size(legacySarPdf.toPath())).isEqualTo(Files.size(newSarPdf.toPath()))
    assertReportContentsEquals(getDocument(legacySarPdf), getDocument(legacySarPdf))
  }

  private fun assertReportContentsEquals(legacyDoc: Document, newDoc: Document) {
    legacyDoc.use {
      newDoc.use {
        val legacyPdf = legacyDoc.pdfDocument
        val newPdf = newDoc.pdfDocument

        assertThat(legacyPdf.numberOfPages).isEqualTo(newPdf.numberOfPages)

        for (i in 1 until legacyPdf.numberOfPages) {
          val originalPage = PdfTextExtractor.getTextFromPage(legacyPdf.getPage(i))
          val refactorPage = PdfTextExtractor.getTextFromPage(newPdf.getPage(i))

          assertThat(refactorPage)
            .withFailMessage(
              "Refactored PDF did not match legacy PDF content. Diff: (Page $i) \"${
                StringUtils.difference(
                  originalPage,
                  refactorPage,
                )
              }\"",
            )
            .isEqualTo(originalPage)
        }
      }
    }
  }

  private fun generateLegacyReport(params: ReportParameters): Path {
    return legacyPdfService.execute(
      services = params.services,
      nomisId = params.nomisId,
      ndeliusCaseReferenceId = params.ndeliusCaseReferenceId,
      sarCaseReferenceNumber = params.sarCaseReferenceNumber,
      subjectName = params.subjectName,
      dateFrom = params.dateFrom,
      dateTo = params.dateTo,
      subjectAccessRequest = params.subjectAccessRequest,
      pdfStream = ByteArrayOutputStream(),
    ).use { stream ->
      Files.write(tempDir.resolve("sar-legacy.pdf"), stream.toByteArray())
    }
  }

  private fun generateNewReport(params: ReportParameters): Path {
    return newPdfService.generateSubjectAccessRequestPDF(params).use { stream ->
      Files.write(tempDir.resolve("sar-new.pdf"), stream.toByteArray())
    }
  }

  fun getDocument(file: File): Document = Document(PdfDocument(PdfReader(file)))

  fun getTestData(): Any? {
    return PdfServiceTest::class.java.classLoader.getResourceAsStream(TEST_DATA_PATH)?.let {
      InputStreamReader(it).use { reader ->
        val map: Map<*, *> = Gson().fromJson(reader, Map::class.java)
        map["content"] as Any
      }
    }
  }
}
