apiVersion: v2
appVersion: '1.0'
description: A Helm chart for Kubernetes
name: hmpps-subject-access-request-worker
version: 0.2.0
dependencies:
  - name: generic-service
    version: "3.12"
    repository: https://ministryofjustice.github.io/hmpps-helm-charts
  - name: generic-service
    alias: gotenberg
    version: "3.12"
    repository: https://ministryofjustice.github.io/hmpps-helm-charts
  - name: generic-service
    alias: wiremock
    version: "3.12"
    repository: https://ministryofjustice.github.io/hmpps-helm-charts
    condition: wiremock.enabled
  - name: generic-prometheus-alerts
    version: "1.16"
    repository: https://ministryofjustice.github.io/hmpps-helm-charts
