generic-service:
  nameOverride: hmpps-subject-access-request-worker
  productId: "DPS083"

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-subject-access-request-worker
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-subject-access-request-worker-cert

  resources:
    limits:
      memory: 3Gi
    requests:
      memory: 2Gi

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx2g"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-subject-access-request-worker:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SENTRY_DSN: "SENTRY_DSN"

    rds-instance-output:
      DATABASE_ENDPOINT: "rds_instance_endpoint"
      DATABASE_NAME: "database_name"
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"

    service-urls:
      G1_API_URL: "G1_API_URL"
      G2_API_URL: "G2_API_URL"
      G3_API_URL: "G3_API_URL"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-subject-access-request-worker
