generic-service:
  nameOverride: hmpps-subject-access-request-worker
  serviceAccountName: hmpps-subject-access-request
  productId: "DPS083"

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-subject-access-request-worker
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-subject-access-request-worker-cert

  resources:
    limits:
      memory: 3Gi
    requests:
      memory: 2Gi

  env:
    JAVA_OPTS: "-Xmx2g"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    TASK_SCHEDULING_POOL_SIZE: 1
    GOTENBERG_API_URL: "http://hmpps-subject-access-request-worker-gotenberg"

  namespace_secrets:
    hmpps-subject-access-request-worker:
      SENTRY_DSN: "SENTRY_DSN"
    hmpps-subject-access-request-worker-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-subject-access-request-worker-client-creds:
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"

    rds-instance-output:
      DATABASE_ENDPOINT: "rds_instance_endpoint"
      DATABASE_NAME: "database_name"
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"

    service-urls:
      G1_API_URL: "G1_API_URL"
      G2_API_URL: "G2_API_URL"
      G3_API_URL: "G3_API_URL"

    hmpps-subject-access-request-s3:
      HMPPS_S3_SUBJECT_ACCESS_REQUEST_BUCKET: "bucket_name"

  allowlist:
    groups:
      - internal

gotenberg:
  nameOverride: gotenberg
  replicaCount: 2

  image:
    repository: gotenberg/gotenberg
    tag: 8
    port: 3000

  ingress:
    enabled: false

  livenessProbe:
    httpGet:
      path: /health
    periodSeconds: 30
    initialDelaySeconds: 60
    timeoutSeconds: 20
    failureThreshold: 10

  readinessProbe:
    httpGet:
      path: /health
    periodSeconds: 20
    initialDelaySeconds: 60
    timeoutSeconds: 30
    failureThreshold: 15

  podSecurityContext:
    fsGroup: 1001

  securityContext:
    runAsUser: 1001
    privileged: false
    runAsNonRoot: true

wiremock:
  enabled: false
  nameOverride: wiremock
  replicaCount: 1

  image:
    repository: wiremock/wiremock
    tag: 3x
    port: 8080

  ingress:
    enabled: true

  livenessProbe:
    httpGet:
      path: /__admin/health
    periodSeconds: 30
    initialDelaySeconds: 60
    timeoutSeconds: 20
    failureThreshold: 10

  readinessProbe:
    httpGet:
      path: /__admin/health
    periodSeconds: 20
    initialDelaySeconds: 60
    timeoutSeconds: 30
    failureThreshold: 15

  podSecurityContext:
    fsGroup: 1001

  securityContext:
    runAsUser: 1001
    privileged: false
    runAsNonRoot: true

generic-prometheus-alerts:
  targetApplication: hmpps-subject-access-request-worker
