---
# Per environment values which override defaults in hmpps-subject-access-request-worker/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    host: subject-access-request-worker-dev.hmpps.service.justice.gov.uk

  env:
    SPRING_PROFILES_ACTIVE: dev
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    SENTRY_ENV: dev

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
