---
# Per environment values which override defaults in hmpps-subject-access-request-worker/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    host: subject-access-request-worker-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    DOCUMENT_STORAGE_URL: "https://document-api-dev.hmpps.service.justice.gov.uk"
    PRISON_API_URL: "https://prison-api-dev.prison.service.justice.gov.uk"
    PROBATION_API_URL: "https://subject-access-requests-and-delius-dev.hmpps.service.justice.gov.uk"
    SAR_API_URL: "https://subject-access-request-api-dev.hmpps.service.justice.gov.uk"
    LOCATIONS_API_URL: "https://locations-inside-prison-api-dev.hmpps.service.justice.gov.uk"
    NOMIS_MAPPINGS_API_URL: "https://nomis-sync-prisoner-mapping-dev.hmpps.service.justice.gov.uk"
    SAR_HTML_RENDERER_API_URL: "https://subject-access-request-html-renderer-dev.hmpps.service.justice.gov.uk"
    HTML_RENDERER_ENABLED: true
    S3_PROVIDER: "aws"
    SENTRY_ENV: dev
    BACKLOG_REQUEST_API_ENABLED: true
    BACKLOG_REQUEST_PROCESSOR_ENABLED: false
    BACKLOG_REQUEST_PROCESSOR_INTERVAL: 5
    BACKLOG_REQUEST_PROCESSOR_INITIAL_DELAY: 10
    BACKLOG_REQUEST_PROCESSOR_POOL_SIZE: 10
    TASK_SCHEDULING_POOL_SIZE: 1


# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps_tech_non_prod
