name: Upload WireMock Mappings

on:
  workflow_call:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: Make script executable
      run: chmod +x ./scripts/wiremock-mappings.sh
    - name: Run upload script
      run: ./scripts/wiremock-mappings.sh
