name: Upload WireMock Mappings

on:
  workflow_call:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Make script executable
      run: chmod +x ./scripts/wiremock-mappings.sh
    - name: Run upload script
      run: ./scripts/wiremock-mappings.sh
